AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack principal del sistema

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        FRONTEND_ORIGIN: !Ref FrontendOrigin
        SECURITY_JWT_KEY: !Ref SecurityJwtKey
        SECURITY_JWT_ACCESS_EXPIRATION: !Ref SecurityJwtAccessExpiration
        SECURITY_JWT_REFRESH_EXPIRATION: !Ref SecurityJwtRefreshExpiration
        SECURITY_JWT_USER_GENERATOR: !Ref SecurityJwtUserGenerator
        SECURITY_JWT_HASHED_SECRET: !Ref SecurityJwtHashedSecret
        BCRYPT_SALT_ROUNDS: !Ref BcryptSaltRounds
        DATABASE_URL: !Ref DatabaseUrl
        LAMBDA_EXECUTION_ROLE: !Ref LambdaExecutionRole
        S3_VIDEOS_BUCKET: !Ref S3VideosBucket
        S3_REGION: !Ref S3Region
        # AWS_ACCESS_KEY_ID: !Ref AwsAccessKeyId
        # AWS_SECRET_ACCESS_KEY: !Ref AwsSecretAccessKey
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  NodeEnv:
    Type: String
  FrontendOrigin:
    Type: String
  SecurityJwtKey:
    Type: String
  SecurityJwtAccessExpiration:
    Type: String
  SecurityJwtRefreshExpiration:
    Type: String
  SecurityJwtUserGenerator:
    Type: String
  SecurityJwtHashedSecret:
    Type: String
  BcryptSaltRounds:
    Type: String
  DatabaseUrl:
    Type: String
  LambdaExecutionRole:
    Type: String
  S3VideosBucket:
    Type: String
  S3Region:
    Type: String
  # AwsAccessKeyId:
  #  Type: String
  # AwsSecretAccessKey:
  #  Type: String

Resources:
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/infrastructure/lambdas/auth/template.yml
      Parameters:
        NodeEnv: !Ref NodeEnv
        SecurityJwtKey: !Ref SecurityJwtKey
        SecurityJwtAccessExpiration: !Ref SecurityJwtAccessExpiration
        SecurityJwtRefreshExpiration: !Ref SecurityJwtRefreshExpiration
        SecurityJwtUserGenerator: !Ref SecurityJwtUserGenerator
        SecurityJwtHashedSecret: !Ref SecurityJwtHashedSecret
        BcryptSaltRounds: !Ref BcryptSaltRounds
        DatabaseUrl: !Ref DatabaseUrl

  UserDetailsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/infrastructure/lambdas/userDetails/template.yml
      Parameters:
        NodeEnv: !Ref NodeEnv
        SecurityJwtKey: !Ref SecurityJwtKey
        SecurityJwtAccessExpiration: !Ref SecurityJwtAccessExpiration
        SecurityJwtRefreshExpiration: !Ref SecurityJwtRefreshExpiration
        SecurityJwtUserGenerator: !Ref SecurityJwtUserGenerator
        SecurityJwtHashedSecret: !Ref SecurityJwtHashedSecret
        BcryptSaltRounds: !Ref BcryptSaltRounds
        DatabaseUrl: !Ref DatabaseUrl

  VideosStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/infrastructure/lambdas/videos/template.yml
      Parameters:
        NodeEnv: !Ref NodeEnv
        SecurityJwtKey: !Ref SecurityJwtKey
        SecurityJwtAccessExpiration: !Ref SecurityJwtAccessExpiration
        SecurityJwtRefreshExpiration: !Ref SecurityJwtRefreshExpiration
        SecurityJwtUserGenerator: !Ref SecurityJwtUserGenerator
        SecurityJwtHashedSecret: !Ref SecurityJwtHashedSecret
        BcryptSaltRounds: !Ref BcryptSaltRounds
        DatabaseUrl: !Ref DatabaseUrl
        LambdaExecutionRole: !Ref LambdaExecutionRole
        S3VideosBucket: !Ref S3VideosBucket
        S3Region: !Ref S3Region
        # AwsAccessKeyId: !Ref AwsAccessKeyId
        # AwsSecretAccessKey: !Ref AwsSecretAccessKey
    
  subscriptionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/infrastructure/lambdas/subscription/template.yml
      Parameters:
        NodeEnv: !Ref NodeEnv
        SecurityJwtKey: !Ref SecurityJwtKey
        SecurityJwtAccessExpiration: !Ref SecurityJwtAccessExpiration
        SecurityJwtRefreshExpiration: !Ref SecurityJwtRefreshExpiration
        SecurityJwtUserGenerator: !Ref SecurityJwtUserGenerator
        SecurityJwtHashedSecret: !Ref SecurityJwtHashedSecret
        BcryptSaltRounds: !Ref BcryptSaltRounds
        DatabaseUrl: !Ref DatabaseUrl
        