AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack principal del sistema

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        NODE_ENV: development
        # Security variables
        SECURITY_JWT_KEY: some_jwt_key
        SECURITY_JWT_ACCESS_EXPIRATION: some_access_expiration
        SECURITY_JWT_REFRESH_EXPIRATION: some_refresh_expiration
        SECURITY_JWT_USER_GENERATOR: some_user_generator
        SECURITY_JWT_HASHED_SECRET: some_hashed_secret
        BCRYPT_SALT_ROUNDS: some_number
        # Database variables
        DATABASE_URL: some_db_url

Resources:
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/infrastructure/lambdas/auth/template.yml
      Parameters:
        NODE_ENV: development
        SECURITY_JWT_KEY: some_jwt_key
        SECURITY_JWT_ACCESS_EXPIRATION: some_access_expiration
        SECURITY_JWT_REFRESH_EXPIRATION: some_refresh_expiration
        SECURITY_JWT_USER_GENERATOR: some_user_generator
        SECURITY_JWT_HASHED_SECRET: some_hashed_secret
        BCRYPT_SALT_ROUNDS: some_number
        DATABASE_URL: some_db_url
