AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NODE_ENV:
    Type: String
  SECURITY_JWT_KEY:
   Type: String
  SECURITY_JWT_ACCESS_EXPIRATION:
   Type: String
  SECURITY_JWT_REFRESH_EXPIRATION:
   Type: String
  SECURITY_JWT_USER_GENERATOR:
   Type: String
  SECURITY_JWT_HASHED_SECRET:
   Type: String
  BCRYPT_SALT_ROUNDS:
    Type: String
  DATABASE_URL:
    Type: String
  # S3 Paramenters
  LAMBDA_EXECUTION_ROLE: 
    type: string
  S3_VIDEOS_BUCKET:
    type: string
  S3_REGION: 
    type: string
  AWS_ACCESS_KEY_ID:
    Type: String
  AWS_SECRET_ACCESS_KEY:
    Type: String

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref NODE_ENV
        SECURITY_JWT_KEY: !Ref SECURITY_JWT_KEY
        SECURITY_JWT_ACCESS_EXPIRATION: !Ref SECURITY_JWT_ACCESS_EXPIRATION
        SECURITY_JWT_REFRESH_EXPIRATION: !Ref SECURITY_JWT_REFRESH_EXPIRATION
        SECURITY_JWT_USER_GENERATOR: !Ref SECURITY_JWT_USER_GENERATOR
        SECURITY_JWT_HASHED_SECRET: !Ref SECURITY_JWT_HASHED_SECRET
        BCRYPT_SALT_ROUNDS: !Ref BCRYPT_SALT_ROUNDS
        DATABASE_URL: !Ref DATABASE_URL
        LAMBDA_EXECUTION_ROLE: !Ref LAMBDA_EXECUTION_ROLE
        S3_VIDEOS_BUCKET: !Ref S3_VIDEOS_BUCKET
        S3_REGION: !Ref S3_REGION
        AWS_ACCESS_KEY_ID: !Ref AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: !Ref AWS_SECRET_ACCESS_KEY

Resources:
  SaveVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/saveVideo/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LAMBDA_EXECUTION_ROLE
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /videos/saveVideo
            Method: POST

  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/generatePresignedUrl/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LAMBDA_EXECUTION_ROLE
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /videos/generatePresignedUrl
            Method: POST

  GetVideosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/getVideos/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LAMBDA_EXECUTION_ROLE
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /videos/getVideos
            Method: GET

