AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack hijo de Videos usando API Gateway con CORS

Parameters:
  NodeEnv:
    Type: String
  SecurityJwtKey:
    Type: String
  SecurityJwtAccessExpiration:
    Type: String
  SecurityJwtRefreshExpiration:
    Type: String
  SecurityJwtUserGenerator:
    Type: String
  SecurityJwtHashedSecret:
    Type: String
  BcryptSaltRounds:
    Type: String
  DatabaseUrl:
    Type: String
  LambdaExecutionRole:
    Type: String
  S3VideosBucket:
    Type: String
  S3Region:
    Type: String

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        SECURITY_JWT_KEY: !Ref SecurityJwtKey
        SECURITY_JWT_ACCESS_EXPIRATION: !Ref SecurityJwtAccessExpiration
        SECURITY_JWT_REFRESH_EXPIRATION: !Ref SecurityJwtRefreshExpiration
        SECURITY_JWT_USER_GENERATOR: !Ref SecurityJwtUserGenerator
        SECURITY_JWT_HASHED_SECRET: !Ref SecurityJwtHashedSecret
        BCRYPT_SALT_ROUNDS: !Ref BcryptSaltRounds
        DATABASE_URL: !Ref DatabaseUrl
        LAMBDA_EXECUTION_ROLE: !Ref LambdaExecutionRole
        S3_VIDEOS_BUCKET: !Ref S3VideosBucket
        S3_REGION: !Ref S3Region
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  SaveVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/saveVideo/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LambdaExecutionRole
      Events:
        SaveVideo:
          Type: Api
          Properties:
            Path: /videos/saveVideo
            Method: POST

  GetVideoByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/getVideoById/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LambdaExecutionRole
      Events:
        GetVideoById:
          Type: Api
          Properties:
            Path: /videos/findById/{videoId}
            Method: GET

  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/generatePresignedUrl/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LambdaExecutionRole
      Events:
        GeneratePresignedUrl:
          Type: Api
          Properties:
            Path: /videos/generatePresignedUrl
            Method: POST

  GetVideosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/getVideos/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LambdaExecutionRole
      Events:
        GetVideos:
          Type: Api
          Properties:
            Path: /videos/getVideos
            Method: GET

  GetVideoUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/videos/getVideoUrl/handler.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Role: !Ref LambdaExecutionRole
      Events:
        GetVideoUrl:
          Type: Api
          Properties:
            Path: /videos/getVideoUrl
            Method: POST

Outputs:
  SaveVideoEndpoint:
    Description: "Endpoint para guardar videos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/videos/saveVideo"
    Export:
      Name: SaveVideoEndpoint

  GetVideoByIdEndpoint:
    Description: "Endpoint para obtener video por ID"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/videos/findById/{videoId}"
    Export:
      Name: GetVideoByIdEndpoint

  GeneratePresignedUrlEndpoint:
    Description: "Endpoint para generar URL presignada"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/videos/generatePresignedUrl"
    Export:
      Name: GeneratePresignedUrlEndpoint

  GetVideosEndpoint:
    Description: "Endpoint para obtener todos los videos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/videos/getVideos"
    Export:
      Name: GetVideosEndpoint

  GetVideoUrlEndpoint:
    Description: "Endpoint para obtener la URL de un video"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/videos/getVideoUrl"
    Export:
      Name: GetVideoUrlEndpoint
