AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NodeEnv:
    Type: String
  SecurityJwtKey:
    Type: String
  SecurityJwtAccessExpiration:
    Type: String
  SecurityJwtRefreshExpiration:
    Type: String
  SecurityJwtUserGenerator:
    Type: String
  SecurityJwtHashedSecret:
    Type: String
  BcryptSaltRounds:
    Type: String
  DatabaseUrl:
    Type: String

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        SECURITY_JWT_KEY: !Ref SecurityJwtKey
        SECURITY_JWT_ACCESS_EXPIRATION: !Ref SecurityJwtAccessExpiration
        SECURITY_JWT_REFRESH_EXPIRATION: !Ref SecurityJwtRefreshExpiration
        SECURITY_JWT_USER_GENERATOR: !Ref SecurityJwtUserGenerator
        SECURITY_JWT_HASHED_SECRET: !Ref SecurityJwtHashedSecret
        BCRYPT_SALT_ROUNDS: !Ref BcryptSaltRounds
        DATABASE_URL: !Ref DatabaseUrl

Resources:
  FindUserDetailsByUserIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/userDetails/findById/findUserDetailByUserId.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Events:
        GetUserDetails:
          Type: Api
          Properties:
            Path: /userDetails
            Method: GET

Outputs:
  GetUserDetailsEndpoint:
    Description: "Endpoint para obtener detalles de usuario"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/userDetails"
    Export:
      Name: GetUserDetailsEndpoint
