AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NodeEnv:
    Type: String
  SecurityJwtKey:
    Type: String
  SecurityJwtAccessExpiration:
    Type: String
  SecurityJwtRefreshExpiration:
    Type: String
  SecurityJwtUserGenerator:
    Type: String
  SecurityJwtHashedSecret:
    Type: String
  BcryptSaltRounds:
    Type: String
  DatabaseUrl:
    Type: String

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        SECURITY_JWT_KEY: !Ref SecurityJwtKey
        SECURITY_JWT_ACCESS_EXPIRATION: !Ref SecurityJwtAccessExpiration
        SECURITY_JWT_REFRESH_EXPIRATION: !Ref SecurityJwtRefreshExpiration
        SECURITY_JWT_USER_GENERATOR: !Ref SecurityJwtUserGenerator
        SECURITY_JWT_HASHED_SECRET: !Ref SecurityJwtHashedSecret
        BCRYPT_SALT_ROUNDS: !Ref BcryptSaltRounds
        DATABASE_URL: !Ref DatabaseUrl

Resources:
  AuthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/auth/login/login.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Events:
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST

  AuthRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/auth/regsiter/register.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Events:
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST

  AuthRefreshFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/infrastructure/lambdas/auth/refresh.handler
      CodeUri: ../../../../dist
      Runtime: nodejs20.x
      Events:
        Refresh:
          Type: Api
          Properties:
            Path: /auth/refresh
            Method: POST

Outputs:
  AuthLoginEndpoint:
    Description: "Endpoint para login"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/login"
    Export:
      Name: AuthLoginEndpoint

  AuthRegisterEndpoint:
    Description: "Endpoint para registro"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/register"
    Export:
      Name: AuthRegisterEndpoint

  AuthRefreshEndpoint:
    Description: "Endpoint para refresh de tokens"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/refresh"
    Export:
      Name: AuthRefreshEndpoint
